version: "3.9"

services:
  api:
    build: .
    command: ["uvicorn", "services.api.app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    volumes: [".:/app"]
    environment:
      LOG_LEVEL: "INFO"
    ports:
      - "8000:8000"

  dashboard:
    build: ./dashboard
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes: ["./dashboard:/app"]
    ports:
      - "3000:3000"

  # optional Redis if you decide to cache
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
