# Branch protection rules for main branch
branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - lint
          - test
          - build-and-push
        strict: true  # Require branches to be up to date before merging
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
