helmDefaults:
  atomic: true
  wait: true
  timeout: 600

repositories:
  - name: redpanda
    url: https://charts.redpanda.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  # Kafka‑compatible log store
  - name: redpanda
    namespace: kafka
    chart: redpanda/redpanda
    version: 5.1.4   # keep loose pin; bump in one place later
    values:
      - values/redpanda.yaml        # stub created below

  # OLTP store for trade & coeff snapshots
  - name: postgres
    namespace: db
    chart: bitnami/postgresql
    version: 15.2.5
    values:
      - values/postgres.yaml

  # Low‑latency cache for IV surface & coeffs
  - name: redis
    namespace: cache
    chart: bitnami/redis
    version: 19.3.2
    values:
      - values/redis.yaml

  # Monitoring stack (Prometheus Operator + Grafana)
  - name: kube-prom-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 58.1.1
    values:
      - values/kps.yaml

  - name: grafana-dash
    namespace: monitoring
    chart: grafana/grafana
    # pin minor for plugin compatibility
    version: 7.3.0
    values:
      - values/grafana.yaml
      - values/grafana-dashboard-kpi-ribbon.json
      - values/grafana-dashboard-edge-histogram.json
