repositories:
  - name: bitnami
    url:  https://charts.bitnami.com/bitnami
  - name: redpanda
    url:  https://charts.redpanda.com
  - name: prometheus-community
    url:  https://prometheus-community.github.io/helm-charts
  - name: grafana
    url:  https://grafana.github.io/helm-charts

releases:
  # ---------- Redpanda (Kafka API) ----------
  - name: redpanda
    namespace: data
    chart: redpanda/redpanda
    version: 5.7.60
    values: [values/redpanda-values.yaml]

  # ---------- Postgres (stateful business DB) ----------
  - name: postgres
    namespace: data
    chart: bitnami/postgresql
    version: 15.2.7
    values: [values/postgres-values.yaml]

  # ---------- Redis (Param server + cache) ----------
  - name: redis
    namespace: data
    chart: bitnami/redis
    version: 19.5.4
    values: [values/redis-values.yaml]

  # ---------- Prometheus Operator ----------
  - name: kube-promstack
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    version: 58.6.1
    values: [values/prometheus-values.yaml]

  # ---------- Grafana ----------
  - name: grafana
    namespace: observability
    chart: grafana/grafana
    version: 7.3.9
    values: [values/grafana-values.yaml]
