name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {contents: read, id-token: write}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: gha-terraform@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      - run: echo "build stub"
