name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {contents: read, id-token: write}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        if: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER != '' && secrets.GCP_PROJECT_ID != '' }}
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: gha-terraform@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      - run: echo "build stub"
      - name: Helmfile lint
        run: |
          sudo apt-get install -y helm
          curl -sSL https://github.com/helmfile/helmfile/releases/download/v0.155.0/helmfile_0.155.0_linux_amd64.tar.gz | tar -xz
          sudo mv helmfile /usr/local/bin/
          cd infra
          helmfile lint
  test-ingestor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Unit tests (ingestor)
        run: |
          cd services/ingestor
          pip install poetry
          poetry install --with dev
          poetry run pytest -q

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start services and run integration tests
        run: |
          docker compose -f docker-compose.dev.yml up -d
          pytest integration-tests -q
