name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {contents: read, id-token: write}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        if: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER != '' && secrets.GCP_PROJECT_ID != '' }}
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: gha-terraform@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      - run: echo "build stub"
      - name: Helmfile lint
        run: |
          sudo apt-get install -y helm
          curl -sSL https://github.com/helmfile/helmfile/releases/download/v0.155.0/helmfile_0.155.0_linux_amd64.tar.gz | tar -xz
          sudo mv helmfile /usr/local/bin/
          cd infra
          helmfile lint
